In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
data =  pd.read_csv("/content/drive/MyDrive/id tech/ML projects/project 3 iron feed/MiningProcess_Flotation_Plant_Database- iDTech.csv")

In [ ]:
data.head(2)

,date,% Iron Feed,% Silica Feed,Starch Flow,Amina Flow,Ore Pulp Flow,Ore Pulp pH,Ore Pulp Density,Flotation Column 01 Air Flow,Flotation Column 02 Air Flow,...,Flotation Column 07 Air Flow,Flotation Column 01 Level,Flotation Column 02 Level,Flotation Column 03 Level,Flotation Column 04 Level,Flotation Column 05 Level,Flotation Column 06 Level,Flotation Column 07 Level,% Iron Concentrate,% Silica Concentrate
0,2017-03-10 01:00:00,"55,2","16,98","3019,53","557,434","395,713","10,0664","1,74","249,214","253,235",...,"250,884","457,396","432,962","424,954","443,558","502,255","446,37","523,344","66,91","1,31"
1,2017-03-10 01:00:00,"55,2","16,98","3024,41","563,965","397,383","10,0672","1,74","249,719","250,532",...,"248,994","451,891","429,56","432,939","448,086","496,363","445,922","498,075","66,91","1,31"

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 737453 entries, 0 to 737452
Data columns (total 24 columns):
 #   Column                        Non-Null Count   Dtype
---  ------                        --------------   -----
 0   date                          737453 non-null  object
 1   % Iron Feed                   737453 non-null  object
 2   % Silica Feed                 737453 non-null  object
 3   Starch Flow                   737453 non-null  object
 4   Amina Flow                    737453 non-null  object
 5   Ore Pulp Flow                 737453 non-null  object
 6   Ore Pulp pH                   737453 non-null  object
 7   Ore Pulp Density              737453 non-null  object
 8   Flotation Column 01 Air Flow  737453 non-null  object
 9   Flotation Column 02 Air Flow  737453 non-null  object
 10  Flotation Column 03 Air Flow  737453 non-null  object
 11  Flotation Column 04 Air Flow  737453 non-null  object
 12  Flotation Column 05 Air Flow  737453 non-null  object
 13  Flotation Column 06 Air Flow  737453 non-null  object
 14  Flotation Column 07 Air Flow  737453 non-null  object
 15  Flotation Column 01 Level     737453 non-null  object
 16  Flotation Column 02 Level     737453 non-null  object
 17  Flotation Column 03 Level     737453 non-null  object
 18  Flotation Column 04 Level     737453 non-null  object
 19  Flotation Column 05 Level     737453 non-null  object
 20  Flotation Column 06 Level     737453 non-null  object
 21  Flotation Column 07 Level     737453 non-null  object
 22  % Iron Concentrate            737453 non-null  object
 23  % Silica Concentrate          737453 non-null  object
dtypes: object(24)
memory usage: 135.0+ MB

In [ ]:
data.isnull().values.any()

False

In [ ]:
len(data)

737453

In [ ]:
data = data.drop_duplicates()

In [ ]:
len(data)

736282

In [ ]:
data.columns

Index(['date', '% Iron Feed', '% Silica Feed', 'Starch Flow', 'Amina Flow',
       'Ore Pulp Flow', 'Ore Pulp pH', 'Ore Pulp Density',
       'Flotation Column 01 Air Flow', 'Flotation Column 02 Air Flow',
       'Flotation Column 03 Air Flow', 'Flotation Column 04 Air Flow',
       'Flotation Column 05 Air Flow', 'Flotation Column 06 Air Flow',
       'Flotation Column 07 Air Flow', 'Flotation Column 01 Level',
       'Flotation Column 02 Level', 'Flotation Column 03 Level',
       'Flotation Column 04 Level', 'Flotation Column 05 Level',
       'Flotation Column 06 Level', 'Flotation Column 07 Level',
       '% Iron Concentrate', '% Silica Concentrate'],
      dtype='object')

In [ ]:
len(data.columns)

24

In [ ]:
df = data[['% Iron Feed', '% Silica Feed', 'Starch Flow', 'Amina Flow','% Iron Concentrate', '% Silica Concentrate']]

In [ ]:
df.head()

,% Iron Feed,% Silica Feed,Starch Flow,Amina Flow,% Iron Concentrate,% Silica Concentrate
0,"55,2","16,98","3019,53","557,434","66,91","1,31"
1,"55,2","16,98","3024,41","563,965","66,91","1,31"
2,"55,2","16,98","3043,46","568,054","66,91","1,31"
3,"55,2","16,98","3047,36","568,665","66,91","1,31"
4,"55,2","16,98","3033,69","558,167","66,91","1,31"

In [ ]:
df=df.replace('\,','',regex=True).astype(float)

In [ ]:
df.head(2)

,% Iron Feed,% Silica Feed,Starch Flow,Amina Flow,% Iron Concentrate,% Silica Concentrate
0,552.0,1698.0,301953.0,557434.0,6691.0,131.0
1,552.0,1698.0,302441.0,563965.0,6691.0,131.0

In [ ]:
data[['% Iron Feed', '% Silica Feed', 'Starch Flow', 'Amina Flow','% Iron Concentrate', '% Silica Concentrate']] = df[['% Iron Feed', '% Silica Feed', 'Starch Flow', 'Amina Flow','% Iron Concentrate', '% Silica Concentrate']]

In [ ]:
data.head(2)

,date,% Iron Feed,% Silica Feed,Starch Flow,Amina Flow,Ore Pulp Flow,Ore Pulp pH,Ore Pulp Density,Flotation Column 01 Air Flow,Flotation Column 02 Air Flow,...,Flotation Column 07 Air Flow,Flotation Column 01 Level,Flotation Column 02 Level,Flotation Column 03 Level,Flotation Column 04 Level,Flotation Column 05 Level,Flotation Column 06 Level,Flotation Column 07 Level,% Iron Concentrate,% Silica Concentrate
0,2017-03-10 01:00:00,552.0,1698.0,301953.0,557434.0,"395,713","10,0664","1,74","249,214","253,235",...,"250,884","457,396","432,962","424,954","443,558","502,255","446,37","523,344",6691.0,131.0
1,2017-03-10 01:00:00,552.0,1698.0,302441.0,563965.0,"397,383","10,0672","1,74","249,719","250,532",...,"248,994","451,891","429,56","432,939","448,086","496,363","445,922","498,075",6691.0,131.0

In [ ]:
status = np.where(data["% Iron Feed"]<data["% Iron Concentrate"], 'Profit', 'Loss')

In [ ]:
data['status'] = status

In [ ]:
data[data['status']== 'profit']

Empty DataFrame
Columns: [date, % Iron Feed, % Silica Feed, Starch Flow, Amina Flow, Ore Pulp Flow, Ore Pulp pH, Ore Pulp Density, Flotation Column 01 Air Flow, Flotation Column 02 Air Flow, Flotation Column 03 Air Flow, Flotation Column 04 Air Flow, Flotation Column 05 Air Flow, Flotation Column 06 Air Flow, Flotation Column 07 Air Flow, Flotation Column 01 Level, Flotation Column 02 Level, Flotation Column 03 Level, Flotation Column 04 Level, Flotation Column 05 Level, Flotation Column 06 Level, Flotation Column 07 Level, % Iron Concentrate, % Silica Concentrate, status]
Index: []

[0 rows x 25 columns]

In [ ]:
# data[data['status']== 'Loss']

data.head(2)

,date,% Iron Feed,% Silica Feed,Starch Flow,Amina Flow,Ore Pulp Flow,Ore Pulp pH,Ore Pulp Density,Flotation Column 01 Air Flow,Flotation Column 02 Air Flow,...,Flotation Column 01 Level,Flotation Column 02 Level,Flotation Column 03 Level,Flotation Column 04 Level,Flotation Column 05 Level,Flotation Column 06 Level,Flotation Column 07 Level,% Iron Concentrate,% Silica Concentrate,status
0,2017-03-10 01:00:00,552.0,1698.0,301953.0,557434.0,"395,713","10,0664","1,74","249,214","253,235",...,"457,396","432,962","424,954","443,558","502,255","446,37","523,344",6691.0,131.0,Profit
1,2017-03-10 01:00:00,552.0,1698.0,302441.0,563965.0,"397,383","10,0672","1,74","249,719","250,532",...,"451,891","429,56","432,939","448,086","496,363","445,922","498,075",6691.0,131.0,Profit

In [ ]:
data['status'].value_counts()

Profit    655996
Loss       80286
Name: status, dtype: int64

In [ ]:
data.isna().any()

date                            False
% Iron Feed                     False
% Silica Feed                   False
Starch Flow                     False
Amina Flow                      False
Ore Pulp Flow                   False
Ore Pulp pH                     False
Ore Pulp Density                False
Flotation Column 01 Air Flow    False
Flotation Column 02 Air Flow    False
Flotation Column 03 Air Flow    False
Flotation Column 04 Air Flow    False
Flotation Column 05 Air Flow    False
Flotation Column 06 Air Flow    False
Flotation Column 07 Air Flow    False
Flotation Column 01 Level       False
Flotation Column 02 Level       False
Flotation Column 03 Level       False
Flotation Column 04 Level       False
Flotation Column 05 Level       False
Flotation Column 06 Level       False
Flotation Column 07 Level       False
% Iron Concentrate              False
% Silica Concentrate            False
status                          False
dtype: bool

In [ ]:
data.head(2)

,date,% Iron Feed,% Silica Feed,Starch Flow,Amina Flow,Ore Pulp Flow,Ore Pulp pH,Ore Pulp Density,Flotation Column 01 Air Flow,Flotation Column 02 Air Flow,...,Flotation Column 01 Level,Flotation Column 02 Level,Flotation Column 03 Level,Flotation Column 04 Level,Flotation Column 05 Level,Flotation Column 06 Level,Flotation Column 07 Level,% Iron Concentrate,% Silica Concentrate,status
0,2017-03-10 01:00:00,552.0,1698.0,301953.0,557434.0,"395,713","10,0664","1,74","249,214","253,235",...,"457,396","432,962","424,954","443,558","502,255","446,37","523,344",6691.0,131.0,Profit
1,2017-03-10 01:00:00,552.0,1698.0,302441.0,563965.0,"397,383","10,0672","1,74","249,719","250,532",...,"451,891","429,56","432,939","448,086","496,363","445,922","498,075",6691.0,131.0,Profit

In [ ]:
Featured_Data = data[['date', '% Iron Feed', '% Silica Feed', 'Starch Flow', 'Amina Flow',
       'Ore Pulp Flow', 'Ore Pulp pH', 'Ore Pulp Density','% Iron Concentrate', '% Silica Concentrate','status']]

In [ ]:
Featured_Data.head(2)

,date,% Iron Feed,% Silica Feed,Starch Flow,Amina Flow,Ore Pulp Flow,Ore Pulp pH,Ore Pulp Density,% Iron Concentrate,% Silica Concentrate,status
0,2017-03-10 01:00:00,552.0,1698.0,301953.0,557434.0,"395,713","10,0664","1,74",6691.0,131.0,Profit
1,2017-03-10 01:00:00,552.0,1698.0,302441.0,563965.0,"397,383","10,0672","1,74",6691.0,131.0,Profit

In [ ]:
Featured_Data.columns

Index(['date', '% Iron Feed', '% Silica Feed', 'Starch Flow', 'Amina Flow',
       'Ore Pulp Flow', 'Ore Pulp pH', 'Ore Pulp Density',
       '% Iron Concentrate', '% Silica Concentrate', 'status'],
      dtype='object')

In [ ]:
len(Featured_Data.columns)

11

In [ ]:
x = data[['% Iron Feed', '% Silica Feed', 'Starch Flow', 'Amina Flow']]

In [ ]:
y = data[['status']]

In [ ]:
y

        status
0       Profit
1       Profit
2       Profit
3       Profit
4       Profit
...        ...
737448  Profit
737449  Profit
737450  Profit
737451  Profit
737452  Profit

[736282 rows x 1 columns]

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size =0.2)

In [ ]:
from sklearn.tree import DecisionTreeClassifier
model = DecisionTreeClassifier()

In [ ]:
model = model.fit(x_train,y_train)

In [ ]:
from sklearn.model_selection import cross_val_score
cross_val_score(model, x ,y , cv=10)

array([0.83721088, 0.7350093 , 0.58557886, 0.69081056, 0.64093823,
       0.67149726, 0.74551801, 0.86871842, 0.76556473, 0.74038409])

In [ ]:
y_pred = model.predict(x_test)

In [ ]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test, y_pred)

array([[  8476,   7498],
       [  7547, 123736]])

In [ ]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test, y_pred)

0.8978316820253027

In [ ]:
from sklearn.metrics import precision_score
precision = precision_score(y_test, y_pred,labels=['Loss', 'Profit'], average='micro' )
print('Precision: %.3f' % precision)

Precision: 0.898

In [ ]:
from sklearn.metrics import recall_score
recall = recall_score(y_test, y_pred,labels=['Loss', 'Profit'], average='micro')
print('Recall: %.3f' % recall)

Recall: 0.898

In [ ]:
from sklearn.metrics import f1_score


score = f1_score(y_test, y_pred, labels=['Loss', 'Profit'], average='micro')
print('F-Measure: %.3f' % score)

F-Measure: 0.898

In [ ]:
from matplotlib import pyplot as plt

In [ ]:
from sklearn.ensemble import RandomForestClassifier

In [ ]:
rfc = RandomForestClassifier(n_estimators=20, criterion='gini',max_depth=5)
rfc.fit(x_train,y_train)
ypred = rfc.predict(x_test)
ypred

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().

array(['Profit', 'Profit', 'Profit', ..., 'Profit', 'Profit', 'Loss'],
      dtype=object)

In [ ]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test, ypred)

0.8956857738511582

In [ ]:
from sklearn.metrics import confusion_matrix,plot_confusion_matrix
conf_mat = confusion_matrix(y_test,y_pred)
conf_mat

array([[  8476,   7498],
       [  7547, 123736]])

In [ ]:
from sklearn.metrics import precision_score
precision = precision_score(y_test, y_pred,labels=['Loss', 'Profit'], average='micro' )
print('Precision: %.3f' % precision)

Precision: 0.898

In [ ]:
from sklearn.metrics import recall_score
recall = recall_score(y_test, y_pred,labels=['Loss', 'Profit'], average='micro')
print('Recall: %.3f' % recall)

Recall: 0.898

In [ ]:
from sklearn.metrics import f1_score


score = f1_score(y_test, y_pred, labels=['Loss', 'Profit'], average='micro')   
print('F-Measure: %.3f' % score)

F-Measure: 0.898